### ISSUE TITLE
Problem when using deepfashion_256_v2.ckpt

### ISSUE THREAD

**Issue by CHNxindong** [soon-yau/upgpt#26]
Thansk for your great work. I have a question:
When I use the deepfashion_256_v2.ckpt checkpoint with upgpt/pt_256/config.yaml, the results are noise (shown as follows)

![image](https://github.com/soon-yau/upgpt/assets/20262070/3e4a7811-0492-46cc-9dbc-d85d1f18d9c0)

But when I use the upgpt.interp256.v1.ckpt and upgpt/interp_256/config.yaml, the results are good. 

It seems that the deepfashion_256_v2.ckpt has some problem. Do you have any suggestion? 

Thanks for your attention!

**Comment by soon-yau** [comment]
Hi XinDong, thanks for your interest. The difference between the two is in the mask where interp_256 uses bounding box, and deepfashion_256_v2 uses human mask. However, the biggest reason is because I accidentally introduced a bug in pixel normalization of the mask when training interp_256 which I left it in the code and hence wouldn't work with the other version. 

Can I ask what do you plan to do with deepfashion_256_v2  that interp_256 couldn't? If it is important, I can try to recall where the bug is and try to fix it.

**Comment by CHNxindong** [comment]
Hi Soon Yau, thanks for your so quick response! Your reply has addressed the issue I mentioned above. 

Now, I hope to fine tune the UPGPT with more data. I have encountered  a new problem:
I followed the steps in DATA_README.md, but I find that there is no scripts.segm_utils in command 'python scripts/segment.py':
![image](https://github.com/soon-yau/upgpt/assets/20262070/9b72ebc0-15b3-4f9a-b3c0-8d0ceff39a66)
Can you kindly share the scripts/segm_utils.py

Thanks for your attention!

**Comment by CHNxindong** [comment]
Hi Soon Yau, thanks for your quick and nice response! I hope to know: 
1. Which YAML file might I use that can work well with deepfashion_256_v2.ckpt? (As I know in your paper, the model trained with human mask is better than that with bounding box)
3. What is the difference between pt256 *.ckpt and interp256 *.ckpt? 

Further, I hope to fine tune the UPGPT with more data. I have encountered a new problem:
I followed the steps in DATA_README.md, but I find that there is no scripts.segm_utils in command 'python scripts/segment.py':
![image](https://github.com/soon-yau/upgpt/assets/20262070/f0398434-9ca2-45ab-9214-2db1881d3875)
Can you kindly share the scripts/segm_utils.py

Thanks for your attention and patience!
