### ISSUE TITLE
The RPM estimated from 2D images

### ISSUE THREAD

**Issue by CHNxindong** [soon-yau/upgpt#29]
Hi, authors. Thanks again for your great work! I have observed that in your training process, the mask is concatenated with the noise. May I kindly inquire if this mask will also be employed during the inference stage? 

(My understanding is that masks derived from 2D images potentially contain target information and thus might not be suitable for use in the inference phase, but I would greatly appreciate clarification on your approach in this regard.)

![image](https://github.com/soon-yau/upgpt/assets/20262070/ad2e6559-6188-4500-8b28-0d8f0ad7e433)

**Comment by soon-yau** [comment]
The mask is also used in inference. The mask we extract is very rough map (not pixel accurate) and I don't think it leaks any info about the people in the dataset. In fact, the final released model in the app uses bounding box which has additional benefit of being interpolatable. 

Generally, condition on parameters e.g. camera translation is weaker than spatial conditioning. I think this is observed on more recent camera control video generation models too. Therefore, we use bounding box / mask to increase the person position, otherwise there can have jitter which artificially degrade similarity score.

**Comment by CHNxindong** [comment]
Thanks for your response! I understand your point now. Could you please share your methodology for extracting the rough map?

**Comment by soon-yau** [comment]
The SMPL pose estimator that I used also produces human mask. I can't immediately recall which repo I used but it was one by Facebook (now Meta). Anyway, you can use any human segmentation tool and I found https://github.com/cxgincsu/SemanticGuidedHumanMatting to be working quite well.

**Comment by CHNxindong** [comment]
I understand your point. Thanks again for your response!

**Comment by junwenxiong** [comment]
@soon-yau Hi, great work, could you please share the pose estimator?

**Comment by soon-yau** [comment]
> @soon-yau Hi, great work, could you please share the pose estimator?

I use the following repo. You can modify demo.py to extract SMPL parameters.
https://github.com/facebookresearch/phosa
